ipfs:
  config:
    Addresses:
      API: "/ip4/0.0.0.0/tcp/5002"
      Swarm:
        - "/ip4/127.0.0.1/tcp/4002"
    Discovery:
      webRTCStar:
        Enabled: false
      MDNS:
        Enabled: false
  EXPERIMENTAL:
    dht: true
    pubsub: true
  env:
  - name: "DEBUG"
    value: "libp2p:pulsarcast*,jsipfs*,floodsub:test*,-jsipfs:trace*"
  resources:
    limits:
      # cpu: 5m
      memory: 512Mi
    requests:
      # cpu: 120m
      memory: 512Mi

  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 120
    timeoutSeconds: 120
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 180
    timeoutSeconds: 180
toxiproxy:
  config:
  - name: "ipfs_swarm"
    listen: "0.0.0.0:8002"
    upstream: "127.0.0.1:4002"
ingress:
  enabled: true
  class: addon-http-application-routing
  host: ec58ca9d2c694c0c9111.eastus.aksapp.io
