ipfs:
  config:
    Addresses:
      API: "/ip4/0.0.0.0/tcp/5002"
      Swarm:
        - "/ip4/127.0.0.1/tcp/4002"
    Discovery:
      webRTCStar:
        Enabled: false
      MDNS:
        Enabled: false
  env:
  - name: "DEBUG"
    value: "libp2p:pulsarcast*,libp2p:dht*,jsipfs*"
  readinessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 20
  livenessProbe:
    initialDelaySeconds: 20
    periodSeconds: 20
    timeoutSeconds: 20
toxiproxy:
  config:
  - name: "ipfs_swarm"
    listen: "0.0.0.0:8002"
    upstream: "127.0.0.1:4002"
