kind: Service
apiVersion: v1
metadata:
  name: ipfs
spec:
  selector:
    app: ipfs
  type: NodePort
  ports:
  - name: swarm
    protocol: TCP
    port: 8002
    targetPort: 4002
  - name: ipfs-api
    protocol: TCP
    port: 5002
    targetPort: 5002
  - name: toxiproxy-api
    protocol: TCP
    port: 8474
    targetPort: 8474
