---
replicaCount: 3

image:
  repository: docker.elastic.co/logstash/logstash
  tag: 6.5.4
  pullPolicy: IfNotPresent

elasticsearch:
  host: elasticsearch-master.elastic
  port: 9200

livenessProbe:
  httpGet:
    path: /
    port: monitor
  initialDelaySeconds: 240
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: monitor
  initialDelaySeconds: 240
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 6
  successThreshold: 1

config:
  xpack.monitoring.enabled: true
  xpack.monitoring.elasticsearch.url: "http://elasticsearch-master.elastic:9200"

filters:
  main: |-
    filter {
      if [beat][name] =~ /^filebeat-.*$/ {
        if [kubernetes][container][name] == "js-ipfs" {
          grok {
            pattern_definitions => {
              "JSON" => "{.*}"
              "MODULE" => "[\w?:]*"
            }   
            match => {
              message => [
                "%{TIMESTAMP_ISO8601:logdate} %{MODULE:module} %{GREEDYDATA:message} %{JSON:data}",
                "%{TIMESTAMP_ISO8601:logdate} %{MODULE:module} %{GREEDYDATA:message}"
              ]   
            }   
            overwrite => [ "message" ]
          }
  
          # Set @timestamp using the date in the log message.
          date {
            match => [ "logdate", "ISO8601" ]
            remove_field => [ "logdate" ]
          }   
  
          if [data] {
            json {
              source => "data"
              target => "data"
            }
          }
        }
      }
    }

