---
replicaCount: 1

image:
  repository: docker.elastic.co/logstash/logstash
  tag: 6.8.4
  pullPolicy: IfNotPresent

elasticsearch:
  host: elasticsearch-master.elastic
  port: 9200

livenessProbe:
  httpGet:
    path: /
    port: monitor
  initialDelaySeconds: 240
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /
    port: monitor
  initialDelaySeconds: 240
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 6
  successThreshold: 1

config:
  xpack.monitoring.enabled: true
  xpack.monitoring.elasticsearch.hosts: "http://elasticsearch-master.elastic:9200"

filters:
  main: |-
    filter {

      # Fingerprint events to avoid duplication
      fingerprint {
        id => "dedup"
        concatenate_all_fields => true
        target => "[@metadata][fingerprint]"
        method => "SHA1"
      }

      if [beat][name] =~ /^filebeat-.*$/ {
        if [kubernetes][container][name] == "js-ipfs" {
          grok {
            id => "ipfs-log-parser"

            pattern_definitions => {
              "JSON" => "{.*}"
              "MODULE" => "[\w?:]*"
            }   

            match => {
              message => [
                "%{TIMESTAMP_ISO8601:logdate} %{MODULE:module} %{GREEDYDATA:message} %{JSON:data}",
                "%{TIMESTAMP_ISO8601:logdate} %{MODULE:module} %{GREEDYDATA:message}"
              ]   
            }   

            overwrite => [ "message" ]
          }
  
          # Set @timestamp using the date in the log message.
          date {
            id => "timestamp"
            match => [ "logdate", "ISO8601" ]
            remove_field => [ "logdate" ]
          }   
  
          if [data] {
            json {
              id => "json-parse"
              source => "data"
              target => "data"
            }
          }
        }
      }
    }

outputs:
  main: |-
    output {
      elasticsearch {
        id => "elasticsearch-output"
        hosts => ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
        manage_template => false
        document_id => "%{[@metadata][fingerprint]}"
        index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
      }
    }
