---
imageTag: 6.8.4
metricbeatConfig:
  kube-state-metrics-metricbeat.yml: |
    metricbeat.modules:
    - module: kubernetes
      enabled: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        # Uncomment this to get k8s events:
        # - event
      period: 2m
      hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
      processors:
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
      # - drop_event:
      #     when:
      #       and:
      #         - not:
      #             has_fields: ["kubernetes.labels.app.kubernetes.io/name"]
      #         - or:
      #           - equals:
      #               kubernetes.labels.app: "logstash"
      #           - equals:
      #               kubernetes.labels.app: "kibana"
      #           - equals:
      #               kubernetes.labels.app: "elasticsearch-master"
      - rename:
          fields:
          - from: "kubernetes.labels.app.kubernetes.io/name"
            to: "kubernetes.labels.app_kubernetes_io/name"
          - from: "kubernetes.labels.app.kubernetes.io/instance"
            to: "kubernetes.labels.app_kubernetes_io/instance"
          - from: "kubernetes.labels.app.kubernetes.io/managed-by"
            to: "kubernetes.labels.app_kubernetes_io/managed-by"
          ignore_missing: true
      - rename:
          when:
            not:
              has_fields: ['kubernetes.labels.app_kubernetes_io/name']
          fields:
            - from: 'kubernetes.labels.app'
              to: 'kubernetes.labels.app_kubernetes_io/name'
      - drop_fields:
          fields:
          - 'kubernetes.labels.app'
      # - drop_fields:
      #     when:
      #       has_fields: ['kubernetes.labels.app_kubernetes_io/name']
      #     fields:
      #     - 'kubernetes.labels.app'
    output:
      logstash:
        enabled: true
        hosts: ["logstash.elastic:5044"]
        compression_level: 6
        timeout: 2m
        pipelining: 2
        bulk_max_size: 1000
    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch-master.elastic:9200"]
    queue.mem:
      # events: 100000
      # flush.min_events: 512
      flush.timeout: 30s
  
  metricbeat.yml: |
    metricbeat.modules:
    - module: kubernetes
      enabled: true
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 2m
      host: "${NODE_NAME}"
      hosts: ["${NODE_NAME}:10255"]
      processors:
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
      # - drop_event:
      #     when:
      #       and:
      #         - not:
      #             has_fields: ["kubernetes.labels.app.kubernetes.io/name"]
      #         - or:
      #           - equals:
      #               kubernetes.labels.app: "logstash"
      #           - equals:
      #               kubernetes.labels.app: "kibana"
      #           - equals:
      #               kubernetes.labels.app: "elasticsearch-master"
      - rename:
          fields:
          - from: "kubernetes.labels.app.kubernetes.io/name"
            to: "kubernetes.labels.app_kubernetes_io/name"
          - from: "kubernetes.labels.app.kubernetes.io/instance"
            to: "kubernetes.labels.app_kubernetes_io/instance"
          - from: "kubernetes.labels.app.kubernetes.io/managed-by"
            to: "kubernetes.labels.app_kubernetes_io/managed-by"
          ignore_missing: true
      - rename:
          when:
            not:
              has_fields: ['kubernetes.labels.app_kubernetes_io/name']
          fields:
            - from: 'kubernetes.labels.app'
              to: 'kubernetes.labels.app_kubernetes_io/name'
      - drop_fields:
          fields:
          - 'kubernetes.labels.app'
      # - drop_fields:
      #     when:
      #       has_fields: ['kubernetes.labels.app_kubernetes_io/name']
      #     fields:
      #     - 'kubernetes.labels.app'
  
    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch-master.elastic:9200"]
    queue.mem:
      # events: 100000
      # flush.min_events: 512
      flush.timeout: 30s
    output:
      logstash:
        enabled: true
        hosts: ["logstash.elastic:5044"]
        timeout: 2m
        compression_level: 6
        pipelining: 2
        bulk_max_size: 1000
