---
esJavaOpts: "-Xmx2g -Xms2g"
imageTag: 6.8.4
resources:
  requests:
    memory: 2Gi
    cpu: 100m
  limits:
    memory: 4Gi
    cpu: 1000m

clusterHealthCheckParams: "wait_for_status=yellow&timeout=5s"

readinessProbe:
  failureThreshold: 8
  initialDelaySeconds: 120
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 30

esConfig:
  elasticsearch.yml: |
    xpack.monitoring.collection.enabled: true
