apiVersion: v1
kind: ConfigMap
metadata:
  name: toxiproxy-config
  namespace: ipfs-testbed
  labels:
    app: ipfs-testbed
data:
  proxy-config.json: |
    [
      {
        "name": "ipfs_swarm",
        "listen": "0.0.0.0:8002",
        "upstream": "0.0.0.0:4002"
      }
    ]
