apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs-testbed
  labels:
    app: ipfs-testbed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-testbed
  template:
    metadata:
      labels:
        app: ipfs-testbed
    spec:
      containers:
      - name: toxiproxy
        image: shopify/toxiproxy
        args: ["--host", "0.0.0.0", "--config", "/etc/toxiproxy-config/proxy-config.json"]
        ports:
        - name: toxiproxy-api
          containerPort: 8474
        - name: toxiproxy-proxy
          containerPort: 8002
        readinessProbe:
          tcpSocket:
            port: toxiproxy-proxy
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: toxiproxy-proxy
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: toxiproxy-config
          mountPath: /etc/toxiproxy-config
          readOnly: true
      - name: js-ipfs
        image: jgantunes/js-ipfs
        ports:
        - name: ipfs-swarm
          containerPort: 4002
        - name: ipfs-api
          containerPort: 5002
        readinessProbe:
          httpGet:
            path: /api/v0/id
            port: ipfs-api
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v0/id
            port: ipfs-api
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: toxiproxy-config
          configMap:
            name: toxiproxy-config
            defaultMode: 0444
