---
elasticsearchHosts: "http://elasticsearch-master.elastic:9200"
imageTag: 6.8.4
resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 200m
kibanaConfig:
  kibana.yml: |
    xpack.reporting.csv.maxSizeBytes: 104857600
    xpack.reporting.queue.timeout: 960000
