---
imageTag: 6.8.4
filebeatConfig:
  filebeat.yml: |
    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch-master.elastic:9200"]
    # queue.mem:
    #   events: 12800
    #   flush.min_events: 3200
      # flush.timeout: 30s
    output:
      # file:
      #   enabled: true
      #   path: "/tmp/filebeat"
      #   filename: filebeat
      logstash:
        hosts: ["logstash.elastic:5044"]
        # compression_level: 9
        # pipelining: 4
        # loadbalance: true
        # worker: 4
        # bulk_max_size: 3200
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      scan_frequency: '1s'
      processors:
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "ipfs-testbed"
      # - drop_event:
      #     when:
      #       and:
      #         - not:
      #             has_fields: ["kubernetes.labels.app.kubernetes.io/name"]
      #         - or:
      #           - equals:
      #               kubernetes.labels.app: "logstash"
      #           - equals:
      #               kubernetes.labels.app: "kibana"
      #           - equals:
      #               kubernetes.labels.app: "elasticsearch-master"
      - rename:
          fields:
          - from: "kubernetes.labels.app.kubernetes.io/name"
            to: "kubernetes.labels.app_kubernetes_io/name"
          - from: "kubernetes.labels.app.kubernetes.io/instance"
            to: "kubernetes.labels.app_kubernetes_io/instance"
          - from: "kubernetes.labels.app.kubernetes.io/managed-by"
            to: "kubernetes.labels.app_kubernetes_io/managed-by"
          ignore_missing: true
      - rename:
          when:
            not:
              has_fields: ['kubernetes.labels.app_kubernetes_io/name']
          fields:
            - from: 'kubernetes.labels.app'
              to: 'kubernetes.labels.app_kubernetes_io/name'
      - drop_fields:
          fields:
          - 'kubernetes.labels.app'
