---
imageTag: 6.8.4
filebeatConfig:
  filebeat.yml: |
    xpack.monitoring:
      enabled: true
      elasticsearch:
        hosts: ["http://elasticsearch-master.elastic:9200"]
    output:
      file:
        enabled: false
      logstash:
        hosts: ["logstash.elastic:5044"]
        compression_level: 6
        pipelining: 2
        bulk_max_size: 3200
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_cloud_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
      - drop_event:
          when:
            not:
              equals:
                kubernetes.namespace: "ipfs-testbed"
      # - drop_event:
      #     when:
      #       and:
      #         - not:
      #             has_fields: ["kubernetes.labels.app.kubernetes.io/name"]
      #         - or:
      #           - equals:
      #               kubernetes.labels.app: "logstash"
      #           - equals:
      #               kubernetes.labels.app: "kibana"
      #           - equals:
      #               kubernetes.labels.app: "elasticsearch-master"
      - rename:
          fields:
          - from: "kubernetes.labels.app.kubernetes.io/name"
            to: "kubernetes.labels.app_kubernetes_io/name"
          - from: "kubernetes.labels.app.kubernetes.io/instance"
            to: "kubernetes.labels.app_kubernetes_io/instance"
          - from: "kubernetes.labels.app.kubernetes.io/managed-by"
            to: "kubernetes.labels.app_kubernetes_io/managed-by"
          ignore_missing: true
      - rename:
          when:
            not:
              has_fields: ['kubernetes.labels.app_kubernetes_io/name']
          fields:
            - from: 'kubernetes.labels.app'
              to: 'kubernetes.labels.app_kubernetes_io/name'
      - drop_fields:
          fields:
          - 'kubernetes.labels.app'
